import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./e2e",
  outputDir: "test-results",
  // The development mock database is shared by all browser sessions.
  fullyParallel: false,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  timeout: 60_000,
  // Fresh development servers compile routes on their first request.
  expect: { timeout: 20_000 },
  reporter: [["list"], ["html", { outputFolder: "playwright-report", open: "never" }]],
  use: {
    baseURL: "http://localhost:3100",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
  projects: [
    { name: "chromium", testIgnore: "**/production-security.spec.ts", use: { ...devices["Desktop Chrome"] } },
    { name: "production-chromium", testMatch: "**/production-security.spec.ts", use: { ...devices["Desktop Chrome"], baseURL: "http://localhost:3200" } },
  ],
  webServer: [{
    command: "npm run dev -- --port 3100",
    url: "http://localhost:3100/auth/sign-in",
    reuseExistingServer: false,
    timeout: 120_000,
    env: {
      ENABLE_MOCK_DB: "true",
      AUTH_SECRET: "playwright-local-only-secret",
      NEXTAUTH_SECRET: "playwright-local-only-secret",
      NEXTAUTH_URL: "http://localhost:3100",
      AUTH_URL: "http://localhost:3100",
      AUTH_TRUST_HOST: "true",
      GITHUB_CONNECTION_CLIENT_ID: "", GITHUB_CONNECTION_CLIENT_SECRET: "",
      GITHUB_CONNECTION_ORIGIN: "", GITHUB_CONNECTION_ENCRYPTION_KEY: "",
      AI_ENABLED: "false",
      NEXT_PUBLIC_COLLABORATION_URL: "",
      COLLABORATION_SECRET: "",
      COLLABORATION_APP_URL: "",
      COLLABORATION_TEST_MODE: "false",
      REDIS_URL: "",
      NEXT_TELEMETRY_DISABLED: "1",
    },
  }, {
    command: "npm run start -- --port 3200",
    url: "http://localhost:3200/auth/sign-in",
    reuseExistingServer: false,
    timeout: 120_000,
    env: {
      ENABLE_MOCK_DB: "false",
      DATABASE_URL: "mongodb://127.0.0.1:27017/liveide-browser-build",
      AUTH_SECRET: "91d76ac0048ef23b594069cdddfe8732b0a516cf7629804ee574312acd852609",
      NEXTAUTH_SECRET: "91d76ac0048ef23b594069cdddfe8732b0a516cf7629804ee574312acd852609",
      AUTH_URL: "http://localhost:3200",
      NEXTAUTH_URL: "http://localhost:3200",
      AUTH_TRUST_HOST: "true",
      AUTH_GITHUB_ID: "", AUTH_GITHUB_SECRET: "",
      AUTH_GOOGLE_ID: "", AUTH_GOOGLE_SECRET: "",
      NEXT_PUBLIC_COLLABORATION_URL: "", COLLABORATION_SECRET: "", COLLABORATION_APP_URL: "",
      COLLABORATION_TEST_MODE: "false", REDIS_URL: "", AI_ENABLED: "false",
      NEXT_TELEMETRY_DISABLED: "1",
    },
  }],
});
